import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";
import { Neo4jGraphQL } from "@neo4j/graphql";
import "dotenv/config.js"; // https://stackoverflow.com/a/65292523
import neo4j from "neo4j-driver";
// import customResolvers from "./customResolvers";

// Define custom resolvers
const customResolvers = {
	Query: {
		personHolidayCount: async (_, { name }, context) => {
			// Implement the custom logic using the Neo4j driver
			const session = context.driver.session();
			try {
				const result = await session.run(
					`MATCH (p:Person {name: $name})-[:ATTENDED]->(h:Holiday)
           RETURN p.name AS personName, COUNT(h) AS holidayCount`,
					{ name },
				);
				const record = result.records[0];
				return {
					personName: record.get("personName"),
					holidayCount: record.get("holidayCount").toInt(),
				};
			} catch (error) {
				throw new Error("Error querying the Neo4j database", { cause: error });
			} finally {
				await session.close();
			}
		},
	},
};

const typeDefs = `#graphql
    type Movie {
        title: String
        actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
    }

    type Actor {
        name: String
        movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
    }

	type Continent {
		name: String!
		nodeId: String!
	}

    type Country {
		name: String!
		nodeId: String!
	}

	type City {
		name: String!
		nodeId: String!
		capital: Boolean!
		level: String
	}

	type Island {
		name: String!
		nodeId: String!
	}

	type Person {
		name: String!
		nodeId: String
		aliases: String
		textBodyText: String
		holidaysAttended: [Holiday!]!
	}

	type Holiday {
		dateYear: String!
		dateMonth: String!
		name: String!
		holidayTitle: String!
		nodeId: String!
		locations: [String!]
		coverPhoto: String
		textHtmlContent: String!
		attendees: [String!]
	}

	type Query {
		personHolidayCount(name: String!): PersonHolidayCount!
	}

	type PersonHolidayCount {
		personName: String!
		holidayCount: Int!
	}
`;

// Display the typeDefs nicely formatted in the console
//console.log("typeDefs from backend/graphql/index.js", typeDefs);

// Display the NEO4J_CREDENTIALS nicely formatted in the console
const NEO4J_CREDENTIALS = `{
	uri: ${process.env.NEO4J_URI},
	user: ${process.env.NEO4J_USER},
	password: ${process.env.NEO4J_PW},
}`;
console.log("NEO4J_CREDENTIALS", NEO4J_CREDENTIALS);

// Connect to Neo4j
const driver = neo4j.driver(
	process.env.NEO4J_URI, // Use 127.0.0.1 instead of localhost - https://stackoverflow.com/a/73777897
	neo4j.auth.basic(process.env.NEO4J_USER, process.env.NEO4J_PW),
);

// const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

// Generate the initial schema
const neoSchema = new Neo4jGraphQL({
	typeDefs,
	driver,
	resolvers: customResolvers,
});

// Build the schema
const schema = await neoSchema.getSchema();

// Get auto-generated schema from neoSchema
// const autoGeneratedSchema = await neoSchema.getSchema();

// Combine auto-generated resolvers and typeDefs with custom resolvers
// const schema = makeExecutableSchema({
// 	typeDefs: autoGeneratedSchema.typeDefs,
// 	resolvers: [autoGeneratedSchema.resolvers, customResolvers],
// });

// Now neoSchema includes both the generated resolvers from your typeDefs
// as well as any custom resolvers you have defined.
// const server = new ApolloServer({
// 	schema: await neoSchema.getSchema(), // This now includes custom resolvers
// 	context: ({ req }) => ({
// 		req,
// 		driver,
// 	}),
// });

const server = new ApolloServer({
	schema,
	context: ({ req }) => ({
		req,
		driver,
	}),
});

const { url } = await startStandaloneServer(server, {
	context: async ({ req }) => ({ req }),
	listen: { port: 4000 },
});

console.log(`🚀 Server ready at ${url}`);

// const server = new ApolloServer({
// 	schema: await neoSchema.getSchema(),
// });

// const { url } = await startStandaloneServer(server, {
// 	context: async ({ req }) => ({ req }),
// 	listen: { port: 4000 },
// });

// // Display the url
// console.log(`Backend server started up. 🚀 Server ready at ${url}`);
